apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRQXN0TThPcTYyMG83REZrUHQzcHpEVEFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlReU9UY3haVGczWWkxak5ESTRMVFJsTWpVdFlXRmhOeTFpT1dNek9UQmhaR1EwTkRBdwpJQmNOTWpZd01qSXpNRGt6TXpFMFdoZ1BNakExTmpBeU1UWXhNRE16TVRSYU1DOHhMVEFyQmdOVkJBTVRKREk1Ck56RmxPRGRpTFdNME1qZ3ROR1V5TlMxaFlXRTNMV0k1WXpNNU1HRmtaRFEwTURDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQU5WUFdTSm4xdVYvbUNNRVlndkszYnNHVUNzYWZ6Ly9UU1Z5dkFENAorMnVZd2xqK1lUU3hIZml1eGhZenV1eHdHQXdoc0hRVFVua2JSSzNyOWFsMTNkWTZCY2RpMGZvUXBud21yVjBVCjkxZ2gzWVJxaFRwTzdkUUczd0g3OWx2NVlxc2ZWak43YXlpM3JtUU1oMHRJUUxUMWxwNFZub3p5dlcrSHFMbmsKYlZoRnBVbXJzS1Y4VFJPdmo0SExVYVlaS2lyRmd6VWRZSlhoZHRIZDB0R2JlbE5EQm00RW5PNkxFU2p0eFFpMgpvelhzM0hqK0ZHZ2NlSVg2b3JrKytEOFQ0YW1Fb2sweHBMVGZRZ3RrWDhJbFY0YjZ4YjdGMkpmTlZMdzlGbDNzCk16cWNaOVR2ZTNTZHhlUXhmWjBHVkVpTjNnODloRWR1amtNdTJObmVsbldocUNycEZWRStaWmdzVmFZcGdhRWMKYnRUSnhHdDZWUXpVbGwrRkJIOThST0Y4cW8wYXZxNHVua1B5aW9hQnRUU1FZUDRjSi8rRXJGblR6ek1OaFlJbgpaUkhQRmZ6aE4zSmZkakV0NHdMeEJzQzY5TjFxUXZJRzdPdDBUTXpMMFdzTDVpS2l2UkU4Qkx1a01ZSXRkZWRBClFkTjFkMjJSZlFaV3EvcG5UMkppc3dTRklRSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVISlhpdWtXWnI5MjJXbmxEYlBPZjhnREJDWmd3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFCbXl1U0lLMWlQdSs0RC8zM3Ezb0NhNzdRMHRHVmtNQk9sUm9yYjQvU1VSClVzV2RRTENhTmI3UXhRR1dJNnByVXk2bjJOTVdoRXFvRXBUamdnQVdRaE9kSFl1WFViMjI3bnRVTjNzUjFHYTgKZjloeGhSVEhkSkVvVVdFTlZ2QUtYdjJlMWRRU0krTHJPT0ZBNGpiUjl6VkJRZnpvVWV3MC94MlBDTitUc05HegpTUjRFREdzbDhqVkhLMnpvMXZPbjBQVjdienh3WGZvSVZuVTU3a3JUeWlTUDRISTU2RzI2TjdLWk1EZWhmTUdKCnRCZEhMYmZPTHpEanFURTRjNE9YZEZmd2dNMy82RzJITzJ6VFpEbmcvVWhuUFNRbmlodHhpRmFZejRXN2h4Zk0KNTR6dnJCZXl5V3VseUtZUE5wcDM1UDlvT0xtV2Q0dTJEK2hJZU12bUNLaGxWUS83WSt3dllUWHVNQkN0eGllSApWTkZnQXk0dGpxakVkUEFIT0o3UWNSbGlZdXNjMjRYZzRnRGhrTi9pWlRFV25GYVhhSDREam14SHU1ZENFZ2g4Cml4cDBheGFSODdsamNxRllPR1NxU1pmUTh4S3BsR0QwMzJOdGxQVlJQSTNRUXhtSndsd3J3RHlzeDFqem54Q08KUnlZTU5sT1RLQkNGMCtsWVhiQmdWdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://34.159.118.117
  name: gke_project-cea37556-bc1e-4fd1-801_europe-west3-c_tech-stack-cluster
contexts:
- context:
    cluster: gke_project-cea37556-bc1e-4fd1-801_europe-west3-c_tech-stack-cluster
    user: gke_project-cea37556-bc1e-4fd1-801_europe-west3-c_tech-stack-cluster
  name: gke_project-cea37556-bc1e-4fd1-801_europe-west3-c_tech-stack-cluster
current-context: gke_project-cea37556-bc1e-4fd1-801_europe-west3-c_tech-stack-cluster
kind: Config
users:
- name: gke_project-cea37556-bc1e-4fd1-801_europe-west3-c_tech-stack-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
      interactiveMode: IfAvailable
      provideClusterInfo: true
